#!/bin/bash
sudo yum update -y

sudo yum install -y httpd httpd-tools mod_ssl

sudo systemctl start httpd

sudo systemctl enable httpd

sudo amazon-linux-extras | grep php

sudo amazon-linux-extras enable php7.4

sudo yum clean metadata

sudo yum install php php-common php-pear -y

sudo yum install php-{cgi,curl,mbstring,gd,mysqlnd,gettext,json,xml,fpm,intl,zip}

sudo rpm -Uvh https://dev.mysql.com/get/mysql57-community-release-el7-11.noarch.rpm

sudo yum install mysql-community-server -y

sudo systemctl enable mysqld

sudo systemctl start mysqld

